version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: idle_rpg_postgres
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: idle_rpg

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./RPG API/IdleRpgApi
      dockerfile: Dockerfile
    container_name: idle_rpg_backend
    depends_on:
      - postgres

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=idle_rpg;Username=admin;Password=admin123

    ports:
      - "5000:8080"

volumes:
  pgdata: